"""
agents/orchestrator.py
───────────────────────
OrchestratorAgent — the central coordinator of the MAGE pipeline.

Responsibilities:
    • Receive the user's analytical goal and expertise level.
    • Decompose the goal into a sequence of sub-tasks via a ReAct-style loop
      (Reason → Act → Observe → repeat).
    • Dispatch sub-tasks to the appropriate specialist agents.
    • Collect and aggregate outputs into a unified EDA result.
    • Consult the RAG layer for grounded recommendations.

ReAct Loop (skeleton):
    Each iteration consists of:
        1. REASON  — inspect current state, decide next action.
        2. ACT     — call the relevant specialist agent.
        3. OBSERVE — record the agent's output; update state.
    The loop terminates when all sub-tasks are resolved or a step limit is hit.
"""

from __future__ import annotations

import logging
from typing import Any

from agents.ingestion_agent import IngestionAgent
from agents.mining_agent import MiningAgent
from agents.visualization_agent import VisualizationAgent
from agents.recommendation_agent import RecommendationAgent

logger = logging.getLogger(__name__)

# Maximum number of ReAct iterations before the loop halts.
MAX_REACT_STEPS = 10


class OrchestratorAgent:
    """
    Goal-conditioned orchestrator that drives the full MAGE EDA pipeline.

    The orchestrator owns the ReAct loop and coordinates all specialist
    agents.  It is the *only* agent that has direct knowledge of the other
    agents; specialist agents are deliberately isolated from each other.
    """

    def __init__(self) -> None:
        self._ingestion = IngestionAgent()
        self._mining = MiningAgent()
        self._visualization = VisualizationAgent()
        self._recommendation = RecommendationAgent()

        # Ordered plan: each entry is a (agent_name, agent_instance) tuple.
        # In future iterations this plan will be dynamically generated by an LLM.
        self._default_plan: list[tuple[str, Any]] = [
            ("IngestionAgent", self._ingestion),
            ("MiningAgent", self._mining),
            ("VisualizationAgent", self._visualization),
            ("RecommendationAgent", self._recommendation),
        ]

    # ── Public API ────────────────────────────────────────────────────────────

    def run(
        self,
        goal: str,
        expertise_level: str = "intermediate",
        data: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Execute the ReAct-style EDA pipeline for the given goal.

        Parameters
        ----------
        goal : str
            Natural-language analytical goal from the user.
        expertise_level : str
            One of "beginner", "intermediate", "expert".
        data : dict, optional
            Arbitrary context/data payload forwarded to each agent.

        Returns
        -------
        dict
            Aggregated result containing steps, recommendations, rag_sources,
            and a high-level summary.
        """
        logger.info("OrchestratorAgent.run() | goal=%r expertise=%s", goal, expertise_level)

        context: dict[str, Any] = {
            "goal": goal,
            "expertise_level": expertise_level,
            "data": data or {},
        }
        steps: list[dict[str, Any]] = []

        # ── ReAct Loop ────────────────────────────────────────────────────────
        for step_idx, (agent_name, agent) in enumerate(self._default_plan):
            if step_idx >= MAX_REACT_STEPS:
                logger.warning("ReAct step limit (%d) reached — halting.", MAX_REACT_STEPS)
                break

            # 1. REASON — decide what to do next (placeholder logic)
            thought = self._reason(step_idx, agent_name, context)
            logger.debug("THOUGHT [%d]: %s", step_idx, thought)

            # 2. ACT — invoke the specialist agent
            try:
                output = agent.run(context=context)
                status = "success"
            except Exception as exc:  # noqa: BLE001
                logger.exception("Agent %s raised an exception: %s", agent_name, exc)
                output = {"error": str(exc)}
                status = "error"

            # 3. OBSERVE — record the result and update context
            step_result = {"agent": agent_name, "status": status, "output": output}
            steps.append(step_result)
            context[f"{agent_name}_output"] = output

        # ── Aggregate ─────────────────────────────────────────────────────────
        return self._aggregate(goal, expertise_level, steps, context)

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _reason(self, step: int, agent_name: str, context: dict[str, Any]) -> str:
        """
        Generate a reasoning thought for the current ReAct step.

        TODO: Replace with an LLM call (e.g. GPT-4o / Claude) that reads
              the context and decides whether to call the agent, skip it,
              or revise the plan.
        """
        return (
            f"Step {step}: Running {agent_name} to advance goal '{context['goal']}'."
        )

    def _aggregate(
        self,
        goal: str,
        expertise_level: str,
        steps: list[dict[str, Any]],
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Combine specialist agent outputs into a unified pipeline result.

        TODO: Replace dummy placeholders with real aggregation logic.
        """
        return {
            "goal": goal,
            "expertise_level": expertise_level,
            "steps": steps,
            "recommendations": [
                "[DUMMY] Recommendation 1 — placeholder until RAG is wired.",
                "[DUMMY] Recommendation 2 — placeholder until RAG is wired.",
            ],
            "rag_sources": ["[DUMMY] knowledge_base/eda_best_practices.md"],
            "summary": (
                f"[DUMMY] Analysis of goal '{goal}' completed in {len(steps)} steps."
            ),
        }
